### ISSUE TITLE
a0fun, etc?

### ISSUE THREAD

**Issue by chrishwiggins** [royarkaprava/TVBARC#1]
https://github.com/royarkaprava/TVBARC/blob/3e468d979c49af51f10e7586e787369549da88ff/example-code.R#L29

sorry, where are a0fun, etc defined in this line?

**Comment by royarkaprava** [comment]
I am sorry. I should have deleted that line. That line is not required. All the required coefficient functions are defined from line 34-36. I shall delete that as soon as possible.

Thank you for your interest.
