### ISSUE TITLE
g?

### ISSUE THREAD

**Issue by chrishwiggins** [royarkaprava/TVBARC#2]
https://github.com/royarkaprava/TVBARC/blob/564f64929bf8eaee43828baff3cbc68c56a7ac6d/example-code.R#L29

any suggestions on what value i should set for "g"?

**Comment by royarkaprava** [comment]
Sorry I deleted the line somehow. I updated the code. 'g' is sequence between [0,1].

I added the line.
g=(1:resolution)/resolution

**Comment by chrishwiggins** [comment]
w00t! thanks much! some students are presenting on your work on wednesday they will be grateful you made time to look into this
