### ISSUE TITLE
slow; maybe change params for 'example'?

### ISSUE THREAD

**Issue by chrishwiggins** [royarkaprava/TVBARC#3]
https://github.com/royarkaprava/TVBARC/blob/02454b8b934125abfe35b6ca85f22e5cb2342646/example-code.R#L3

when i ran this code it took 1.5 hours on laptop with default parameters. for the example code you might consider allowing smaller values of the MC burn , MC iteration, and overall iteration. with smaller values it's not "research accurate" but allows someone to run once w/o reading code.

also i encourage you to add "source("{filename}")" for the 2 files that are required for hte 2 big UDFs, again, so that someone can just download and run.

here's a modified version of example-code.R which

1. changes the parameters so it runs in seconds rather than 90 min
2. sources the UDFs
3. dumps the output to an Rdata for post-hoc examination (otherwise you run the example w/o output)

==== snip ====

# define UDF fit.tvARMCMCunbd
source('TVBARC.R')
# define UDF fit.tvINGARCHMCMCcombo
source('TVINGARCH.R')

set.seed(1)

iterations <- 10
MC.iter <- 10
MC.burn <- 5

Ti <- iterations
t <- 0:Ti/Ti
mut0 <- exp(-(t-0.5)^2/0.1)
at10 <- 0.3*(t-1)^2 + 0.1
at20 <- rep(0, Ti+1) #0.5*t
datavect <- rep(0, Ti+1)
datavect[1] <- rpois(1, mut0[1])
datavect[2] <- rpois(1, mut0[2]+at10[2]*datavect[1])
for(i in 3:Ti){
  datavect[i] <- rpois(1, mut0[i]+at10[i]*datavect[i-1]+at20[i]*datavect[i-2])
}

data <- datavect[-1]

fit      <- fit.tvARMCMCunbd(data, order= 1 , Total_itr = MC.iter,     burn = MC.burn)
Afnp     <- Reduce('+', fit$Afn) / length(fit$Afn)       #Estimated AR coef fns
mufnp    <- Reduce('+', fit$Mfn) / length(fit$Mfn)       #Estimated mean fn
mufnpder <- Reduce('+', fit$Mfnder) / length(fit$Mfnder) #Estimated derivative of mean fn
Afnpder  <- Reduce('+', fit$Afnder) / length(fit$Afnder) #Estimated derivative of AR coef fns

set.seed(20)
n=200;

resolution=n #means we compute at every 1/n

g=(1:resolution)/resolution

a0 <- 25*exp(-(g-0.5)^2/0.1)
a1 <- 0.3*(g-1)^2+0.1
b1 <- 0.1*(g)^1.5+0.1

e=rnorm(n);x=e;sigma2=array(0,n)
sigma20=a0[1]/(1-b1[1]);x0=rpois(1, sigma20);
sigma2[1]=a0[1]+a1[1]*x0+b1[1]*sigma20;x[1]=rpois(1, sigma2[1])

for (i in 2:n)
{
  sigma2[i]=a0[i]+a1[i]*x[i-1]+b1[i]*sigma2[i-1]
  x[i]= rpois(1, sigma2[i])
}  

fitS <- fit.tvINGARCHMCMCcombo(as.numeric(c(x0,x)), order1 = 1, order2 = 1, norder = 4, knot = 6, Total_itr = MC.iter,  burn =MC.burn)

print("done!")

print(length(fitS$Mfn[[1]]))

mufn_p  <- matrix(unlist(fitS$Mfn), length(fitS$Mfn[[1]]))
Afn_p   <- matrix(unlist(fitS$Afn), length(fitS$Afn[[1]]))
Bfn_p   <- matrix(unlist(fitS$Bfn), length(fitS$Bfn[[1]]))

mufn_p  <- matrix(unlist(fitS$Mfn), length(fitS$Mfn[[1]]))
Afn_p   <- matrix(unlist(fitS$Afn), length(fitS$Afn[[1]]))
Bfn_p   <- matrix(unlist(fitS$Bfn), length(fitS$Bfn[[1]]))

mutp <- rowMeans(mufn_p) #Posterior mean of mean function
Atp  <- rowMeans(Afn_p)  #Posterior mean of AR(1)
Btp  <- rowMeans(Bfn_p)  #Posterior mean of CH(1)

save.image(file = "TVBARC-quick.Rdata")

====

**Comment by royarkaprava** [comment]
Hi Chris,
Thank you so much for your feedback. I very much appreciate your comments. I shall make the changes in the example.R so that it becomes more useful for other users.

-Arkaprava

**Comment by chrishwiggins** [comment]
Hooray!!! Thanks very much!
